### ISSUE TITLE
How jobs are defined with metric sidekiq_jobs_failed_total ?

### ISSUE THREAD

**Issue by cheesepaulo** [yabeda-rb/yabeda-sidekiq#23]
I'm seeing some conflicting values on Appsignal (using Yabeda) and Sentry about some job errors. What define a job as successful or failed?

**Comment by Envek** [comment]
If some exception occurred during job execution job counts as failed: https://github.com/yabeda-rb/yabeda-sidekiq/blob/4ffad774a0949fc1fd84509db52c7537f746d329/lib/yabeda/sidekiq/server_middleware.rb#L20-L22
(unless any other [middleware](https://github.com/mperham/sidekiq/wiki/Middleware) down the stack swallowed the error)

**Comment by Envek** [comment]
Can you please tell what Sidekiq server middlewares you have configured:
```rb
Sidekiq.server_middleware.to_a
```
And your versions of yabeda gems, how you send data to Appsignal, etc?

How exactly values are conflicting?

For example bigger numbers from yabeda may be because yabeda-sidekiq counts every failed retry as a new failure, while Sentry may de-duplicate failures for the same job (or may not – I don't know, it is my guess).

**Comment by cheesepaulo** [comment]
Thanks Envek, the metric was 'wrong' only for a particular job. This job processes a queue, so we only log errors in the sentry but we don't raise the exception so it didn't count as fail in the metric.

Thanks for your help, I looked exactly what I should have looked at.
