### ISSUE TITLE
Start metric server without initializer ?

### ISSUE THREAD

**Issue by arkhamRejek** [yabeda-rb/yabeda-sidekiq#7]
Is there a way to start the server without putting it in an initializer?

**Comment by arkhamRejek** [comment]
just added it to it's own initializer and added a env variable to start

**Comment by Envek** [comment]
But why you don't want to put in an initializer for Sidekiq, [like in example application](https://github.com/yabeda-rb/example-prometheus/blob/f2d03ecef4fc9edf283f69f6854e4486eb3cdc2f/rails_app/config/initializers/sidekiq.rb)?

Also instead of setting env variables you can ask Sidkiq itself whether this process is a worker process or not:
```ruby
Sidekiq.server?
```

**Comment by arkhamRejek** [comment]
@Envek it tried to start the server during our migrations process in our deploy process but it's already running from a previous rails process which calls the initializer. It was making our build error out for our worker & scheduler in our docker containers. So we added a flag to allow us to turn it off, well not turn it off but not to call it because that exception causes our job to exit
